### ISSUE TITLE
update docs for expected keys for jvm options

### ISSUE THREAD

**Issue by jsanda** [datastax/cass-operator#26]
I was trying to run one of the integration tests that was using this manifest:

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.6
  managementApiAuth:
    insecure: {}
  size: 3
  storageConfig:
      cassandraDataVolumeClaimSpec:
        storageClassName: server-storage
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  racks:
    - name: r1
    - name: r2
    - name: r3
  config:
    jvm-server-options:
      initial_heap_size: "800m"
      max_heap_size: "800m"
    cassandra-yaml:
      file_cache_size_in_mb: 100
      memtable_space_in_mb: 100
```
The config init container failed though with this exception:

```
$ kubectl logs cluster1-dc1-r1-sts-0 server-config-init
clojure.lang.ExceptionInfo: throw+: {:type :InvalidConfigKeys, :message "Invalid config keys for DSE version 3.11.6: jvm-server-options"} {:type :InvalidConfigKeys, :message "Invalid config keys for DSE version 3.11.6: jvm-server-options"}
	at slingshot.support$stack_trace.invoke(support.clj:201)
	at com.datastax.configbuilder.build_config$valid_config_keys_QMARK_.invokeStatic(build_config.clj:51)
	at com.datastax.configbuilder.build_config$valid_config_keys_QMARK_.invoke(build_config.clj:43)
	at com.datastax.configbuilder.build_config$build_configs.invokeStatic(build_config.clj:458)
	at com.datastax.configbuilder.build_config$build_configs.invoke(build_config.clj:450)
	at com.datastax.configbuilder.operator$make_configs.invokeStatic(operator.clj:36)
	at com.datastax.configbuilder.operator$make_configs.invoke(operator.clj:9)
	at com.datastax.configbuilder.operator$_main.invokeStatic(operator.clj:56)
	at com.datastax.configbuilder.operator$_main.doInvoke(operator.clj:52)
	at clojure.lang.RestFn.invoke(RestFn.java:397)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.RestFn.applyTo(RestFn.java:132)
	at com.datastax.configbuilder.CassOperatorConfigBuilder.main(Unknown Source)
Error processing request: throw+: {:type :InvalidConfigKeys, :message "Invalid config keys for DSE version 3.11.6: jvm-server-options"}
```

@jimdickinson explained to me that the expected keys are different depending on the server version. They are as follows:

| server version | jmv options key |
| -------------- | :---------------:|
| 3.11                   | jvm-options       |
| 4.0                    | jvm-server-options |
| DSE                  | jvm-server-options |

I wanted to create this ticket since I am not sure if this is documented anywhere. 

I think having a single property name, whether it is `jvm-options` or `jvm-server-options`, that can be used across versions would be even better.

**Comment by jsanda** [comment]
I am closing this since #38 has been merged.
