### ISSUE TITLE
Rolling restart fails with new pod IP address

### ISSUE THREAD

**Issue by jogoertzen-stantec** [datastax/cass-operator#350]
## Environment

Red Hat OpenShift Container Platform 4.5
DataStax Kubernetes Operator for Apache Cassandra 1.4.1

# Reproduction

- create a new CassandraDatacenter

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  serviceAccount: cass-operator
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.6
  managementApiAuth:
    insecure: {}
  size: 3
  serverImage: 'registry.connect.redhat.com/datastax/cassandra:3.11.6-2'
  configBuilderImage: 'registry.connect.redhat.com/datastax/cass-config-builder:1.0.0-2'
  allowMultipleNodesPerWorker: true
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: my-cool-storage-class-name
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  config:
    cassandra-yaml:
      num_tokens: 256
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
    jvm-options:
      initial_heap_size: 4G
      max_heap_size: 4G
      additional-jvm-opts:
        - '-Ddse.system_distributed_replication_dc_names=dc1'
        - '-Ddse.system_distributed_replication_per_dc=3'
```

- wait for the cluster to come up

![image](https://user-images.githubusercontent.com/41205049/103699930-ead1ba00-4f60-11eb-9da8-aa06aff48973.png)

- trigger a rolling restart with `spec.rollingRestartRequested: true`
- wait for the first pod to restart

![image](https://user-images.githubusercontent.com/41205049/103700195-5ddb3080-4f61-11eb-9075-8445aa3f36d6.png)

- find this error message in `server-system-logger` container of new pod

```bash
INFO  [main] 2021-01-05 20:56:14,117 StorageService.java:1478 - JOINING: sleeping 30000 ms for pending range setup
INFO  [main] 2021-01-05 20:56:44,118 StorageService.java:1478 - JOINING: Starting to bootstrap...
ERROR [main] 2021-01-05 20:56:44,155 CassandraDaemon.java:774 - Exception encountered during startup
java.lang.RuntimeException: A node required to move the data consistently is down (/10.201.195.24). If you wish to move the data from a potentially inconsistent replica, restart the node with -Dcassandra.consistent.rangemovement=false
	at org.apache.cassandra.dht.RangeStreamer.getAllRangesWithStrictSourcesFor(RangeStreamer.java:294) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.dht.RangeStreamer.addRanges(RangeStreamer.java:177) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.dht.BootStrapper.bootstrap(BootStrapper.java:87) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.StorageService.bootstrap(StorageService.java:1530) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.StorageService.joinTokenRing(StorageService.java:1024) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:718) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.StorageService.initServer(StorageService.java:652) ~[apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.setup(CassandraDaemon.java:397) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.activate(CassandraDaemon.java:630) [apache-cassandra-3.11.6.jar:3.11.6]
	at org.apache.cassandra.service.CassandraDaemon.main(CassandraDaemon.java:757) [apache-cassandra-3.11.6.jar:3.11.6]
```

## Questions

It seems the rolling restart causes a new pod to be created with a new IP address that the cassandra cluster interprets as just another node attempting to join the cluster, when in fact it should be replacing the old node.

If you are quick, you can catch the cluster status during the brief period where the new node is in the joining state.

![image](https://user-images.githubusercontent.com/41205049/103700327-8bc07500-4f61-11eb-9641-526836c8fb2c.png)

Running this command in the cassandra container of the 'new pod' will cause the dead node to be replaced after a few minutes.

```
echo "JVM_OPTS=\"\$JVM_OPTS -Dcassandra.replace_address=10.201.195.24\"" >> /config/cassandra-env.sh
```

This works, but it will not scale very well as the cluster size grows.

Any idea how we can get rolling restarts working here without having to manually replace dead nodes?

Thanks for reading!

**Comment by jimdickinson** [comment]
@jogoertzen-stantec thanks for the detailed report of your problem! What kind of StorageClass are you using? Something ephemeral? Getting new IPs is normal, but it doesn't cause problems without also losing the storage.

**Comment by jogoertzen-stantec** [comment]
@jimdickinson 

No problem!

I believe the storage is not ephemeral, as when the rolling restart is triggered the persistent volume claim seems to stick around.

Here is the YAML for the actual storage class we are using (ie. not `my-cool-storage-class-name`).

```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: sc-ontap-nas
  selfLink: /apis/storage.k8s.io/v1/storageclasses/sc-ontap-nas
  uid: 80f72305-1fbd-XXXX-XXXX-XXXXXXXXXXXX
  resourceVersion: '10665264'
  creationTimestamp: '2020-03-04T17:02:27Z'
  annotations:
    storageclass.kubernetes.io/is-default-class: 'true'
provisioner: csi.trident.netapp.io
parameters:
  backendType: ontap-nas
  clones: 'true'
  encryption: 'false'
  provisioningType: thin
  snapshots: 'True'
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: Immediate
```

Spinning up a datacenter produces these persistent volume claims.

![image](https://user-images.githubusercontent.com/41205049/105518461-8ff4ce00-5c95-11eb-8edc-4056e0c6245a.png)

Here is the YAML for the first PVC above.

```yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: csi.trident.netapp.io
  selfLink: >-
    /api/v1/namespaces/cassandra/persistentvolumeclaims/server-data-cluster1-dc1-default-sts-0
  resourceVersion: '133521576'
  name: server-data-cluster1-dc1-default-sts-0
  uid: f30345c5-e4df-XXXX-XXXX-XXXXXXXXXXXX
  creationTimestamp: '2021-01-22T16:18:54Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2021-01-22T16:19:14Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:pv.kubernetes.io/bind-completed': {}
            'f:pv.kubernetes.io/bound-by-controller': {}
            'f:volume.beta.kubernetes.io/storage-provisioner': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/managed-by': {}
            'f:cassandra.datastax.com/cluster': {}
            'f:cassandra.datastax.com/datacenter': {}
            'f:cassandra.datastax.com/rack': {}
        'f:spec':
          'f:accessModes': {}
          'f:resources':
            'f:requests':
              .: {}
              'f:storage': {}
          'f:storageClassName': {}
          'f:volumeMode': {}
          'f:volumeName': {}
        'f:status':
          'f:accessModes': {}
          'f:capacity':
            .: {}
            'f:storage': {}
          'f:phase': {}
  namespace: cassandra
  finalizers:
    - kubernetes.io/pvc-protection
  labels:
    app.kubernetes.io/managed-by: cass-operator
    cassandra.datastax.com/cluster: cluster1
    cassandra.datastax.com/datacenter: dc1
    cassandra.datastax.com/rack: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  volumeName: pvc-f30345c5-e4df-XXXX-XXXX-XXXXXXXXXXXX
  storageClassName: sc-ontap-nas
  volumeMode: Filesystem
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
```

Also of note, the events for the the first PVC indicate that the same volume is provisioned twice. This makes sense as it would have have first been provisioned for the "old pod" and then again for the "new pod" after the rolling restart was triggered.

![image](https://user-images.githubusercontent.com/41205049/105520401-ea8f2980-5c97-11eb-8f0a-61be6a7b484c.png)

**Comment by jogoertzen-stantec** [comment]
Also, we did not see any rolling restart issues when using the commercial `datastax/dse-server` image for the datacenter. Here is the YAML we used in this case.

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  configBuilderImage: registry.connect.redhat.com/datastax/cass-config-builder
  serverImage: registry.connect.redhat.com/datastax/dse-server:6.8.3-ubi7
  serviceAccount: cass-operator
  clusterName: cluster1
  serverType: dse
  serverVersion: "6.8.3"
  managementApiAuth:
    insecure: {}
  size: 3
  allowMultipleNodesPerWorker: true
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: sc-ontap-nas
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  config:
    cassandra-yaml:
      num_tokens: 256
      authenticator: com.datastax.bdp.cassandra.auth.DseAuthenticator
      authorizer: com.datastax.bdp.cassandra.auth.DseAuthorizer
      role_manager: com.datastax.bdp.cassandra.auth.DseRoleManager
    jvm-server-options:
      initial_heap_size: "4G"
      max_heap_size: "4G"
      additional-jvm-opts:
        - "-Ddse.system_distributed_replication_dc_names=dc1"
        - "-Ddse.system_distributed_replication_per_dc=3"
```

**Comment by florissmit10** [comment]
We had this problem as wel. I dont know if it has the same cause, since we are using a different image.
In our case the pv was mounted but in the wrong place. These settings made everything work for us:
```yaml
spec: 
  clusterName: cluster1
  config: 
    cassandra-yaml: 
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
      data_file_directories:
      - /var/lib/cassandra/data
      commitlog_directory: /var/lib/cassandra/commitlog
      cdc_raw_directory: /var/lib/cassandra/cdc_raw
      hints_directory: /var/lib/cassandra/hints
      saved_caches_directory: /var/lib/cassandra/saved_caches
```
This actually reconfigures the defaults which were somehow overridden to use /opt/cassandra/data instead of /var/lib/cassandra.

An easy way tot test if this is the cause of your problem is to see if the pv's directory gets populated.

```bash
ls -ll /var/lib/cassandra #They should be here
ls -ll /opt/cassandra/data #not here
```

**Comment by jogoertzen-stantec** [comment]
@florissmit10

Thanks for taking the time to reply as it appears your issue was indeed our issue! 

Here is the datacenter yaml that fixed the rolling restart issue.

```yaml
apiVersion: cassandra.datastax.com/v1beta1
kind: CassandraDatacenter
metadata:
  name: dc1
spec:
  serviceAccount: cass-operator
  clusterName: cluster1
  serverType: cassandra
  serverVersion: 3.11.6
  managementApiAuth:
    insecure: {}
  size: 3
  serverImage: 'registry.connect.redhat.com/datastax/cassandra:3.11.6-2'
  configBuilderImage: 'registry.connect.redhat.com/datastax/cass-config-builder:1.0.0-2'
  allowMultipleNodesPerWorker: true
  storageConfig:
    cassandraDataVolumeClaimSpec:
      storageClassName: sc-ontap-nas
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 50Gi
  config:
    cassandra-yaml:
      num_tokens: 256
      authenticator: org.apache.cassandra.auth.PasswordAuthenticator
      authorizer: org.apache.cassandra.auth.CassandraAuthorizer
      role_manager: org.apache.cassandra.auth.CassandraRoleManager
      data_file_directories:
      - /var/lib/cassandra/data
      commitlog_directory: /var/lib/cassandra/commitlog
      cdc_raw_directory: /var/lib/cassandra/cdc_raw
      hints_directory: /var/lib/cassandra/hints
      saved_caches_directory: /var/lib/cassandra/saved_caches
    jvm-options:
      initial_heap_size: 4G
      max_heap_size: 4G
      additional-jvm-opts:
        - '-Ddse.system_distributed_replication_dc_names=dc1'
        - '-Ddse.system_distributed_replication_per_dc=3'

```
